# docker-compose.yml
version: "3.8"
services:
  db:
    image: mongo
    volumes: 
      - mongodata:/data/db
    ports:
      - 27019:27017
  server: 
    image: my_server:1.0
    depends_on: 
      - db
    env_file:
      - .env
    ports: 
      - 80:3005

volumes:
  mongodata: